### ISSUE TITLE
using pipes to push and pull items cause some crashes

### ISSUE THREAD

**Issue by quakeman00** [canitzp/MiniaturePowerPlant#1]
pipes will push items in the first slot avaliable (the top slot) even if it does not fit (battery) and will suck out every items all the time instead of waiting like the furnase till theyre full / empty.

power saving also dont work properly, it store power on the batteries but the power from the batteries cannot be sucked out of the battery

**Comment by canitzp** [comment]
Please tell me the other mods you're using do I can test it myself. Especially the pipes mod

**Comment by canitzp** [comment]
So for me the more critical issue is the energy not being pulled out. I quickly checked it and indeed it doesn't work. This probably comes from cables not pulling energy out of the block, instead the carrier has to push it's energy out. I'll implement it as soon as possible.
I also check the item pipping soon, but the energy is more critical.

**Comment by canitzp** [comment]
@quakeman00 Your issues with energy and piping are fixed in the latest version 39.4.0. It is already uploaded and approved by curseforge.
